version: "3.9"

services:
  postgres:
    container_name: trelol_postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trelol
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: trelol_api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/web
      - ./api:/api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/trelol
    depends_on:
      - postgres

  web:
    container_name: trelol_web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/web
      - ./api:/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

volumes:
  postgres_data: