name: Build and Push Docker images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare web for Docker build
        run: |
          cp pnpm-lock.yaml web/pnpm-lock.yaml
          echo "packages:" > web/pnpm-workspace.yaml
          echo "  - ." >> web/pnpm-workspace.yaml

      - name: Prepare api for Docker build
        run: |
          cp pnpm-lock.yaml api/pnpm-lock.yaml
          echo "packages:" > api/pnpm-workspace.yaml
          echo "  - ." >> api/pnpm-workspace.yaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push API image
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: veverre/trelol-api:latest
          platforms: linux/amd64

      # Build and push Web image
      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: veverre/trelol-web:latest
          platforms: linux/amd64
